{ pkgs, lib, ... }: {
  isoImage.squashfsCompression = "zstd -Xcompression-level 3";
  boot = {
    kernelPackages = pkgs.linuxPackages_6_15;
    supportedFilesystems.zfs = lib.mkForce false;
    kernelModules = [ "panthor" ];
    kernelParams = [ "console=ttyS2,1500000n8" ];
    initrd.availableKernelModules = lib.mkForce [
      # as you might guess i was quite tired of having random hardware not work in stage 1 of the
      # installer
      "adc_keys"
      "bridge"
      "cdrom"
      "cfg80211"
      "cmdlinepart"
      "dax"
      "display_connector"
      "dm_mod"
      "dmi_sysfs"
      "drm_exec"
      "drm_gpuvm"
      "dw_mmc_rockchip"
      "ffa_core"
      "fuse"
      "gpu_sched"
      "hantro_vpu"
      "ip6t_rpfilter"
      "ip_tables"
      "ipt_rpfilter"
      "iso9660"
      "isofs"
      "llc"
      "macvlan"
      "mc"
      "mmc_block"
      "nf_conntrack"
      "nf_defrag_ipv4"
      "nf_defrag_ipv6"
      "nf_log_syslog"
      "nf_tables"
      "nfnetlink"
      "nft_compat"
      "nls_cp437"
      "nls_iso8859_1"
      "nvme"
      "nvme_auth"
      "nvme_core"
      "optee"
      "panthor"
      "pci_endpoint_test"
      "phy_rockchip_naneng_combphy"
      "phy_rockchip_usbdp"
      "polyval_ce"
      "polyval_generic"
      "pwm_fan"
      "r8169"
      "rfkill"
      "rfkill_gpio"
      "rk805_pwrkey"
      "rockchip_dfi"
      "rockchip_rga"
      "rockchip_saradc"
      "rockchip_thermal"
      "rpmb_core"
      "rtc_hym8563"
      "sch_fq_codel"
      "sdhci_of_dwcmshc"
      "sm4"
      "snd_soc_es8328"
      "snd_soc_es8328_i2c"
      "snd_soc_rockchip_i2s"
      "snd_soc_rockchip_i2s_tdm"
      "snd_soc_simple_amplifier"
      "snd_soc_simple_card"
      "snd_soc_simple_card_utils"
      "spi_rockchip_sfc"
      "stp"
      "tap"
      "typec"
      "uas"
      "uio"
      "uio_pdrv_genirq"
      "v4l2_h264"
      "v4l2_jpeg"
      "v4l2_mem2mem"
      "v4l2_vp9"
      "videobuf2_common"
      "videobuf2_dma_contig"
      "videobuf2_dma_sg"
      "videobuf2_memops"
      "videobuf2_v4l2"
      "videodev"
      "x_tables"
      "xt_LOG"
      "xt_comment"
      "xt_conntrack"
      "xt_pkttype"
      "xt_tcpudp"
    ];
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    kernel.sysctl = { "kernel.dmesg_restrict" = 0; };
  };
}
