test: ENC[AES256_GCM,data:1G0vibE0rKNDkXp+RmdyeF8=,iv:f7Vr083+bhAR60QL/AhEdogagFaD9yciTYqP47BhhPQ=,tag:UDgN6OhOQf4SCO02pr1pBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxeg73875j2hg8dlr76k8xu652dflg6k46jtfv77gsz4ylr0vd4s0ygxkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV2crWlNkVTBjdnd1NVNK
            WnB3THBVNjlLeFd3YmIxNUljTDNSNFhOU21BCkxhQW1xQW1SYTlOWTJ4MjUwK2xR
            TXZDWlRVZjljM1krNXBRQWQ5SGgwbWMKLS0tICtWOWhwbWFOSkI5aWowaVQrMXRx
            MGRMUHlrWnhJNjBqSXJOZ3FsRm5reTgKcXLArOAv5VT6//JSkZZHTuTIsaScu3Ok
            rR+r8bHkedN09+EEqKewzTfzcybtJ4Q1arzbgfbUlbi3D+7lfWDLQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T05:00:19Z"
    mac: ENC[AES256_GCM,data:kw1SsblLx+8+jjHrFceeYeSMvYxtcn548/q1ACb6FGJe6hxkEhCa4bBjC2wwBsufljnziEto6R4UCGuhmuD4gOXJhLN8W7VTg3IkIAA7RFoagp4rAulnWLeGqf8hK+dypKtLRpBLLPkXW5FfhrHN07KO2wJ//sVkXsQdTX8//Gc=,iv:LqMInY5v7MTNPiLQgBFuhIhek1QgHccpiZPSObNw2dE=,tag:7nSGRhtSiJJSVt46wm3oQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
