test: ENC[AES256_GCM,data:1G0vibE0rKNDkXp+RmdyeF8=,iv:f7Vr083+bhAR60QL/AhEdogagFaD9yciTYqP47BhhPQ=,tag:UDgN6OhOQf4SCO02pr1pBA==,type:str]
ca-key.pem: ENC[AES256_GCM,data:xsAYf4cLQHAd8lrDYOv6bNmXwyLjSKGGJJ0Ooi18nw/QlpypgErS81kSJknJc6865ETSv7hi272mpW/6diWcgaW2ZlN0TLa++VsoeGjLkglOfz9OqmnNJok8z8bNFVdeXoJWsewkDAxuheuAmpzbHh2gVR4bQFR3f/5kocK5rkaSaw/Op3Xu,iv:WoY7N7cDtHdPoEIF3OtmWdHR2WuNwBXVft8B5nEAVQs=,tag:P71JOgY9PV1NShk7vuYOvg==,type:str]
sops:
    age:
        - recipient: age1sxeg73875j2hg8dlr76k8xu652dflg6k46jtfv77gsz4ylr0vd4s0ygxkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV2crWlNkVTBjdnd1NVNK
            WnB3THBVNjlLeFd3YmIxNUljTDNSNFhOU21BCkxhQW1xQW1SYTlOWTJ4MjUwK2xR
            TXZDWlRVZjljM1krNXBRQWQ5SGgwbWMKLS0tICtWOWhwbWFOSkI5aWowaVQrMXRx
            MGRMUHlrWnhJNjBqSXJOZ3FsRm5reTgKcXLArOAv5VT6//JSkZZHTuTIsaScu3Ok
            rR+r8bHkedN09+EEqKewzTfzcybtJ4Q1arzbgfbUlbi3D+7lfWDLQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T12:33:31Z"
    mac: ENC[AES256_GCM,data:Fkyw8vOMX/8EyCSwJD0w8VewxlLB7Psr0M7us1ONv3+PftKjBN9EvwSZnnkXNEKWq7mBm9Vs9Yy5zM434/ynbdKXR3j4I5kCK8Tw8rZ+eZkkrgGBqNGxnCliYbJgST+d9Fs7VA3KD7weL6eKgx1V0oMUq6bzxuZqenD+r1U4p4E=,iv:2mqMgcTTdnNwNoQCLZWeVstHz0n1zHmulZDbdIz/g6Q=,tag:GHqDBXpOvRmqzSA/wqsFqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
