[user]
name = "June Rockway"
email = "2367+jrockway@users.noreply.github.com"

[colors]
"working_copy description" = { underline = true }
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

[ui]
default-command = "log"
diff.format = "git"
conflict-marker-style = "git"

[signing]
signing = "drop"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[template-aliases]
'format_short_signature(signature)' = '''
if(signature.email() == "2367+jrockway@users.noreply.github.com",
 raw_escape_sequence("\x1b[38;5;159m")++"J"++
 raw_escape_sequence("\x1b[38;5;211m")++"u"++
 raw_escape_sequence("\x1b[38;5;231m")++"n"++
 raw_escape_sequence("\x1b[38;5;211m")++"e"++
 raw_escape_sequence("\x1b[38;5;159m")++"!"++
 raw_escape_sequence("\x1b[0m")++"",
 coalesce(signature.email(), email_placeholder)
)
'''

[snapshot]
auto-track = "~glob:**/*.secret.*"

[git]
private-commits = 'description(glob:"private:*")'
sign-on-push = true