#-*-Shell-script-*-

if [ -f ~/.nix-profile/etc/profile.d/nix.sh ]; then
    . ~/.nix-profile/etc/profile.d/nix.sh
fi

export PATH="$HOME/.nix-profile/bin:$PATH"

# limits
ulimit -S -c 0

if [[ ! -v SSH_AUTH_SOCK ]]; then
    export SSH_AUTH_SOCK=$(find /tmp/ssh-* -path '*/ssh-*' -name 'agent*' -uid $(id -u) 2>/dev/null| tail -n1)
fi
